### ISSUE TITLE
Bacnet Gateway

### ISSUE THREAD

**Issue by djok** [biancode/node-red-contrib-bacnet#2]
Hi,

I have bacnet gateway with IP address 10.10.10.100
when I run bacwi I get:
bacwi
Received I-Am Request from 1602001, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603018, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603017, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603016, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603015, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603014, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603013, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603012, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603011, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603010, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603009, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603008, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603007, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603006, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603005, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603004, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603003, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603002, MAC = 10.10.10.100.186.192
Received I-Am Request from 1603001, MAC = 10.10.10.100.186.192
Received I-Am Request from 1601000, MAC = 10.10.10.100.186.192
;Device   MAC (hex)            SNET  SADR (hex)           APDU
;-------- -------------------- ----- -------------------- ----
  1602001 0A:0A:0A:64:BA:C0    1602  00:18:71:D1          1476
  1603018 0A:0A:0A:64:BA:C0    1603  00:18:75:CA          1476
  1603017 0A:0A:0A:64:BA:C0    1603  00:18:75:C9          1476
  1603016 0A:0A:0A:64:BA:C0    1603  00:18:75:C8          1476
  1603015 0A:0A:0A:64:BA:C0    1603  00:18:75:C7          1476
  1603014 0A:0A:0A:64:BA:C0    1603  00:18:75:C6          1476
  1603013 0A:0A:0A:64:BA:C0    1603  00:18:75:C5          1476
  1603012 0A:0A:0A:64:BA:C0    1603  00:18:75:C4          1476
  1603011 0A:0A:0A:64:BA:C0    1603  00:18:75:C3          1476
  1603010 0A:0A:0A:64:BA:C0    1603  00:18:75:C2          1476
  1603009 0A:0A:0A:64:BA:C0    1603  00:18:75:C1          1476
  1603008 0A:0A:0A:64:BA:C0    1603  00:18:75:C0          1476
  1603007 0A:0A:0A:64:BA:C0    1603  00:18:75:BF          1476
  1603006 0A:0A:0A:64:BA:C0    1603  00:18:75:BE          1476
  1603005 0A:0A:0A:64:BA:C0    1603  00:18:75:BD          1476
  1603004 0A:0A:0A:64:BA:C0    1603  00:18:75:BC          1476
  1603003 0A:0A:0A:64:BA:C0    1603  00:18:75:BB          1476
  1603002 0A:0A:0A:64:BA:C0    1603  00:18:75:BA          1476
  1603001 0A:0A:0A:64:BA:C0    1603  00:18:75:B9          1476
  1601000 0A:0A:0A:64:BA:C0    0     00                   1476
;
; Total Devices: 20

Is it possible to address bacnet deviceId? 
Currently, I see how to address 10.10.10.100 and all reads came from SADR 0 in my case 1601000, but I need address the other devices.

vbr,
Rosen

**Comment by biancode** [comment]
did you check the [API](https://fh1ch.github.io/node-bacstack/)

**Comment by djok** [comment]
Yes, I can see it!

**Comment by djok** [comment]
"device.deviceId - The BACNET device-id of the detected device" from bacstack.iAm is the key, but is not implemented in bacstack.readProperty.

**Comment by biancode** [comment]
Please, address your that to the library repo.

**Comment by biancode** [comment]
reopen, if library implements the device-id ...

**Comment by djok** [comment]
Hi, Think that the library now supports the device-id ...

vbr,
