### ISSUE TITLE
How do you specify the object id in the node settings of the object type you are trying to read ?

### ISSUE THREAD

**Issue by aniston** [biancode/node-red-contrib-bacnet#3]
Hello, have been trying to implement a simple BACnetr read , got the basic BACnet command node for a simple whois to work, but could not figure out how to do a simple read_prop of the same device , in particular as an example to get the PresentValue(85) of Object analog_value(2) with Object_Id(4) from Device(7682)

without giving the device ip i get Error: ERR_TIMEOUT in the Debug while with the ip i get Error: BacnetError - Class:0 - Code:0

But in the BACnet Read node there is no setting for the object_id.

If possible an example flow of the 3 working nodes would be much helpful.

Regards,
Aniston

**Comment by aniston** [comment]
Got it working, mixed-up using the Instance as the BACnet DeviceId which is a more common way of addressing a BACnet Device and not directly thru its ip address.

incase any other starters stmble on this, some points to note:

- we need to address the BAcnet device by it's BAcnet IP address
- Instance is the ObjectInstance and not to be confused by the BACnet Device Id

**Comment by Saravan95** [comment]
> Got it working, mixed-up using the Instance as the BACnet DeviceId which is a more common way of addressing a BACnet Device and not directly thru its ip address.
> 
> incase any other starters stmble on this, some points to note:
> 
> * we need to address the BAcnet device by it's BAcnet IP address
> * Instance is the ObjectInstance and not to be confused by the BACnet Device Id

Can you please post the configurations of these nodes.

**Comment by mlavelle42** [comment]
I would also like to see the screen grabs of these nodes. I'm not having any luck so far.

**Comment by biancode** [comment]
@aniston could you provide seom of your examples, please?

**Comment by mlavelle42** [comment]
I'm trying to read BACnet points within Node-Red. Form nomenclature seems to differ from what I expected. I set the Type to Analog_Input (but Analog_Value may be the correct selection). 

![image](https://user-images.githubusercontent.com/11968207/64966150-3fcd5680-d86c-11e9-8efa-74fc594f9650.png)

The Instance is, I believe, correct at 2749 (taken from YABE).

![image](https://user-images.githubusercontent.com/11968207/64966384-ab172880-d86c-11e9-8818-ea231602023c.png)

The Property ID is a mystery. I used Present_Value (85)

![image](https://user-images.githubusercontent.com/11968207/64966490-df8ae480-d86c-11e9-8153-587562c476a8.png)

I put the Device Address as the IP of the controller.

![image](https://user-images.githubusercontent.com/11968207/64966653-2f69ab80-d86d-11e9-9d58-9663ab79897c.png)

I'm not sure about the "Interface" - I used the controller IP - doesn't seem appropriate.

![image](https://user-images.githubusercontent.com/11968207/64966760-6049e080-d86d-11e9-97c6-b6f355ab9fe5.png)

Suggestions?

**Comment by juniormercato** [comment]
> Estou tentando ler pontos BACnet dentro do Node-Red. A nomenclatura das formas parece diferir do que eu esperava. Defino o Tipo como Analog_Input (mas Analog_Value pode ser a seleção correta).
> 
> ![imagem](https://user-images.githubusercontent.com/11968207/64966150-3fcd5680-d86c-11e9-8efa-74fc594f9650.png)
> 
> Acredito que a instância esteja correta em 2749 (tirada do YABE).
> 
> ![imagem](https://user-images.githubusercontent.com/11968207/64966384-ab172880-d86c-11e9-8818-ea231602023c.png)
> 
> O ID da propriedade é um mistério. Eu usei o Present_Value (85)
> 
> ![imagem](https://user-images.githubusercontent.com/11968207/64966490-df8ae480-d86c-11e9-8153-587562c476a8.png)
> 
> Coloquei o endereço do dispositivo como o IP do controlador.
> 
> ![imagem](https://user-images.githubusercontent.com/11968207/64966653-2f69ab80-d86d-11e9-9d58-9663ab79897c.png)
> 
> Não tenho certeza de que a "Interface" - usei o IP do controlador - não pareça apropriado.
> 
> ![imagem](https://user-images.githubusercontent.com/11968207/64966760-6049e080-d86d-11e9-97c6-b6f355ab9fe5.png)
> 
> Sugestões?

Hello.
In "interface" use the IP address of the equipment where NODE-RED is installed.
Send some YABE printscreens to verify correct data type.

**Comment by mlavelle42** [comment]
YABE screens.

![image](https://user-images.githubusercontent.com/11968207/64974045-13203b80-d87a-11e9-8c8c-63fea973d843.png)

Analog Input

![image](https://user-images.githubusercontent.com/11968207/64974154-45319d80-d87a-11e9-91b9-7f1884a1a7cb.png)

Still get a Time_Out error

![image](https://user-images.githubusercontent.com/11968207/64974244-6d210100-d87a-11e9-8729-007264e44e5d.png)

Changed the Interface IP to the that of the Pi.

![image](https://user-images.githubusercontent.com/11968207/64974338-9b9edc00-d87a-11e9-8076-c5bb5c30cf82.png)

Still not sure about the Property ID set to 85.

![image](https://user-images.githubusercontent.com/11968207/64974439-d56fe280-d87a-11e9-83eb-4b1760df7af0.png)

Suggestions?

**Comment by juniormercato** [comment]
Changes the netmask to 255.255.255.0

**Comment by mlavelle42** [comment]
Changed netmask. No change in results. Suggestion about Property ID? Is PRESENT_VALUE appropriate to read an analog input?

**Comment by mlavelle42** [comment]
Who Is? doesn't appear to succeed.

![image](https://user-images.githubusercontent.com/11968207/65067731-2e13ae00-d955-11e9-9016-3cc5f4d6b4ba.png)

YABA sees the objects. Any ideas?

**Comment by magicmatt007** [comment]
I've successfully implemented my first BACnet flows. However, I had to google the numbers for property ID and object ID: https://www.controlscourse.com/bacnet-reference/

In above screenshots, I see nice drop downs which show the actual text descriptions for the property IDs. In my installation (Home Assistant, Node Red) I can see these though. How can I make these visible?

![image](https://user-images.githubusercontent.com/58187053/94986821-232cbb00-0562-11eb-8873-c2068e63676e.png)

**Comment by biancode** [comment]
@magicmatt007 I see there is some code at the wrong palce ... you can add an unused write and it should work, doesn't it?

**Comment by tbiss242** [comment]
@magicmatt007 how were you able to solve the ERR_TIMEOUT problem? I still get that error no matter what changes I make. Who Is? seems to be working correctly, but any BACnet Read/Write gives me the timeout error.

**Comment by magicmatt007** [comment]
> @magicmatt007 how were you able to solve the ERR_TIMEOUT problem? I still get that error no matter what changes I make. Who Is? seems to be working correctly, but any BACnet Read/Write gives me the timeout error.

@tbiss242 : I haven't used this for a while but don't think I ever had the ERR_TIMEOUT problem. I only wasn't able to see the property IDs in plain text and had to enter their respective IDs.

**Comment by andreapx** [comment]
> @magicmatt007 how were you able to solve the ERR_TIMEOUT problem? I still get that error no matter what changes I make. Who Is? seems to be working correctly, but any BACnet Read/Write gives me the timeout error.

Hi, sorry for this necropost, but I'm banging my head against the wall! Were you able to solve the ERR_TIMEOUT error?
