### ISSUE TITLE
"Error stopping node: TimeoutError: timed out after 15000ms"

### ISSUE THREAD

**Issue by triDcontrols** [biancode/node-red-contrib-bacnet#4]
Hi, 

Thanks for this node, 

I get this error in node-red, Here is my flow. 
Error: "Error stopping node: TimeoutError: timed out after 15000ms" and no data is being read from bacnet JACE device, only way to remedy this is to reboot the raspberry pi, and on next re-deployment, same error comes up. 

![capture](https://user-images.githubusercontent.com/22411662/35166178-cca597d2-fd05-11e7-9757-b11f5281cf9e.PNG)

my flow.

`[{"id":"9b2352f.6217bb","type":"tab","label":"Flow 1"},{"id":"c3d5cda4.00dac","type":"BACnet-Read","z":"9b2352f.6217bb","name":"AmpsPhaseA","objectType":"0","objectInstance":"3","propertyId":"85","arrayIndex":0,"deviceIPAddress":"192.168.1.250","server":"9ce827d5.f5d878","multipleRead":true,"x":226,"y":160,"wires":[["bd87f70c.039ae8"]]},{"id":"ea0f2044.f8a9c","type":"inject","z":"9b2352f.6217bb","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"3","crontab":"","once":true,"x":79,"y":184,"wires":[["c3d5cda4.00dac","e6c9efb7.a2b85"]]},{"id":"bd87f70c.039ae8","type":"function","z":"9b2352f.6217bb","name":"Filter_AmpsPhaseA","func":"var numval = msg.payload.values[0].values[0].value[0].value || -1;\nmsg.payload = numval.toFixed(1);\nreturn msg;","outputs":1,"noerr":0,"x":423.5,"y":156,"wires":[["b167a608.263d48","779118a3.a89968"]]},{"id":"e6c9efb7.a2b85","type":"BACnet-Read","z":"9b2352f.6217bb","name":"AmpsPhaseB","objectType":"0","objectInstance":"4","propertyId":"85","arrayIndex":0,"deviceIPAddress":"192.168.1.250","server":"9ce827d5.f5d878","multipleRead":true,"x":225,"y":209,"wires":[["1fe13fc6.df35e"]]},{"id":"1fe13fc6.df35e","type":"function","z":"9b2352f.6217bb","name":"Filter_AmpsPhaseB","func":"var numval = msg.payload.values[0].values[0].value[0].value || -1;\nmsg.payload = numval.toFixed(1);\nreturn msg;","outputs":1,"noerr":0,"x":423,"y":204,"wires":[["bd08ba9d.a97c88","24125a17.070b76"]]},{"id":"b167a608.263d48","type":"ui_gauge","z":"9b2352f.6217bb","name":"","group":"9a0e0cd7.5806b","order":1,"width":0,"height":0,"gtype":"gage","title":"Amps Phase A","label":"A","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":627.5,"y":145,"wires":[]},{"id":"bd08ba9d.a97c88","type":"ui_gauge","z":"9b2352f.6217bb","name":"","group":"9a0e0cd7.5806b","order":2,"width":0,"height":0,"gtype":"gage","title":"Amps Phase B","label":"A","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":630,"y":202,"wires":[]},{"id":"779118a3.a89968","type":"ui_chart","z":"9b2352f.6217bb","name":"","group":"85cbd15b.55537","order":1,"width":0,"height":0,"label":"Amps Phase A","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"5","removeOlderPoints":"","removeOlderUnit":"60","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"x":630.5,"y":114,"wires":[[],[]]},{"id":"24125a17.070b76","type":"ui_chart","z":"9b2352f.6217bb","name":"","group":"85cbd15b.55537","order":2,"width":0,"height":0,"label":"Amps Phase B","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"5","removeOlderPoints":"","removeOlderUnit":"60","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"x":634.5,"y":230,"wires":[[],[]]},{"id":"9ce827d5.f5d878","type":"BACnet-Client","z":"","name":"JACE","port":"47808","adpuTimeout":"6000"},{"id":"9a0e0cd7.5806b","type":"ui_group","z":"","name":"Power","tab":"f5696bf6.939128","order":2,"disp":true,"width":"6"},{"id":"85cbd15b.55537","type":"ui_group","z":"","name":"Amps Graphs","tab":"f5696bf6.939128","order":1,"disp":true,"width":"6"},{"id":"f5696bf6.939128","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]`

**Comment by biancode** [comment]
Hi, after import your flow JACE was not used - try that one:

`[{"id":"c9bf04e2.27462","type":"tab","label":"BACnet","disabled":false,"info":""},{"id":"669e45f7.f70edc","type":"inject","z":"c9bf04e2.27462","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"3","crontab":"","once":true,"x":270,"y":160,"wires":[["8198697b.c7a44","c354b6a0.94e51"]]},{"id":"25affc67.a81084","type":"function","z":"c9bf04e2.27462","name":"Filter_AmpsPhaseA","func":"var numval = msg.payload.values[0].values[0].value[0].value || -1;\nmsg.payload = numval.toFixed(1);\nreturn msg;","outputs":1,"noerr":0,"x":674.5,"y":132,"wires":[["58b925e6.aec774","6117f9b2.84fd6"]]},{"id":"6cfb43ee.dfd374","type":"function","z":"c9bf04e2.27462","name":"Filter_AmpsPhaseB","func":"var numval = msg.payload.values[0].values[0].value[0].value || -1;\nmsg.payload = numval.toFixed(1);\nreturn msg;","outputs":1,"noerr":0,"x":674,"y":180,"wires":[["e3b7dfd4.0aaac","51426585.f8bcbc"]]},{"id":"58b925e6.aec774","type":"ui_gauge","z":"c9bf04e2.27462","name":"","group":"e9ed7705.179108","order":1,"width":0,"height":0,"gtype":"gage","title":"Amps Phase A","label":"A","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":878.5,"y":121,"wires":[]},{"id":"e3b7dfd4.0aaac","type":"ui_gauge","z":"c9bf04e2.27462","name":"","group":"e9ed7705.179108","order":2,"width":0,"height":0,"gtype":"gage","title":"Amps Phase B","label":"A","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":881,"y":178,"wires":[]},{"id":"6117f9b2.84fd6","type":"ui_chart","z":"c9bf04e2.27462","name":"","group":"6edcf214.cd688c","order":1,"width":0,"height":0,"label":"Amps Phase A","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"5","removeOlderPoints":"","removeOlderUnit":"60","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"x":880,"y":80,"wires":[[],[]]},{"id":"51426585.f8bcbc","type":"ui_chart","z":"c9bf04e2.27462","name":"","group":"6edcf214.cd688c","order":2,"width":0,"height":0,"label":"Amps Phase B","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"5","removeOlderPoints":"","removeOlderUnit":"60","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"x":880,"y":220,"wires":[[],[]]},{"id":"8198697b.c7a44","type":"BACnet-Read","z":"c9bf04e2.27462","name":"AmpsPhaseA","objectType":"0","objectInstance":"3","propertyId":"85","arrayIndex":0,"deviceIPAddress":"192.168.1.250","server":"1002058b.b930ba","multipleRead":true,"x":477,"y":136,"wires":[["25affc67.a81084"]]},{"id":"c354b6a0.94e51","type":"BACnet-Read","z":"c9bf04e2.27462","name":"AmpsPhaseB","objectType":"0","objectInstance":"4","propertyId":"85","arrayIndex":0,"deviceIPAddress":"192.168.1.250","server":"1002058b.b930ba","multipleRead":true,"x":476,"y":185,"wires":[["6cfb43ee.dfd374"]]},{"id":"e9ed7705.179108","type":"ui_group","z":"","name":"Power","tab":"3e89c26.c3eb0be","order":2,"disp":true,"width":"6"},{"id":"6edcf214.cd688c","type":"ui_group","z":"","name":"Amps Graphs","tab":"3e89c26.c3eb0be","order":1,"disp":true,"width":"6"},{"id":"1002058b.b930ba","type":"BACnet-Client","z":"c9bf04e2.27462","name":"JACE","port":"","adpuTimeout":""},{"id":"3e89c26.c3eb0be","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]`

**Comment by tridiumcontrols** [comment]
hmm, still getting the same error, Error: "Error stopping node: TimeoutError: timed out after 15000ms

on each redeployment the error comes up, on initial node-red startup after reboot, is fine, and bacnet works great all week, but when i make a change and redeploy, the error comes up.

**Comment by biancode** [comment]
sounds like a problem with the close of the BACnet client ...

**Comment by triDcontrols** [comment]
is the issue in the node or bacstack library?

**Comment by biancode** [comment]
I have to test in the next few days.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by triDcontrols** [comment]
Thanks, looking forward to your findings.

**Comment by triDcontrols** [comment]
@biancode I know you're busy and appreciate all the work you do,  wondering if you had a chance to look into this timeout issue?

**Comment by triDcontrols** [comment]
@tadzil are you having this issue like I am?

**Comment by tadzil** [comment]
Yes, I have. But this affects only deploying of flow, by slowing it (deploy). BACnet nodes are working well.

**Comment by biancode** [comment]
You could test v0.0.13 but maybe it does not work, then we have to wait for the next update of [bacstack](https://github.com/fh1ch/node-bacstack/issues).

**Comment by triDcontrols** [comment]
Thanks for the release, can confirm 0.0.13 works, do not get the time out errors, I'm polling multiple points at 1 second intervals and tried redeploy multiple times without an issue. Awesome work. Thanks. This can be closed now.
