### ISSUE TITLE
Unable to do a BACnet read from a BACnet Simulator

### ISSUE THREAD

**Issue by siddharthtaunk** [biancode/node-red-contrib-bacnet#5]
Hi,

I am successfully able to connect to a **BACnet Simulator** 
but I am not able to read the **present value** from it 

I am attaching the snapshot of the configuration I made and the response from the servers

Kindly help.
Regards.
Siddharth

Image from simulator
![image](https://user-images.githubusercontent.com/27369953/35183105-88b07f0e-fe06-11e7-8f2c-62834bf80828.png)

image of the node red
![image](https://user-images.githubusercontent.com/27369953/35183226-6d872140-fe08-11e7-8fa5-7e5a322d7a85.png)

read properties
![image](https://user-images.githubusercontent.com/27369953/35183238-a3a07682-fe08-11e7-9744-6415e29e0ab8.png)

**Comment by biancode** [comment]
I am sorry, my trial version is locked of that simulator.

**Comment by siddharthtaunk** [comment]
Any other simulators which you recommend?

**Comment by biancode** [comment]
I am sorry, but I had no time to search. If you find one, then please let me know!

**Comment by tridiumcontrols** [comment]
try open source, YABE, yet another bacnet explorer that can launch a bacnet server, after YABE install navigate to program files> yabe> addon and demoserver.exe, works well. 

https://sourceforge.net/projects/yetanotherbacnetexplorer/

**Comment by biancode** [comment]
YABE works ... now I start more tests

**Comment by biancode** [comment]
Please, test v0.0.13 - but maybe it has too many issues from bacstack beta13 for now - Yabe did not work for now, but maybe some other BACnet server.

**Comment by biancode** [comment]
I am sorry, but we have to wait a bit for the next updates of [bacstack](https://github.com/fh1ch/node-bacstack/issues) ...

**Comment by biancode** [comment]
please test v0.1.0
