### ISSUE TITLE
BACnet Write node test

### ISSUE THREAD

**Issue by tadzil** [biancode/node-red-contrib-bacnet#6]
Hello,
I'm using your great BACnet toolbox and have some suggestions.
For the BACnet Write node, would be nice to have one more configuration element: bacnetValueType of written value. Can be selected from list, like "Type" property. Now I have to add it via function block.
![image](https://user-images.githubusercontent.com/1118900/36346211-dcec5262-1442-11e8-882b-0cad2e4f6aa1.png)
This type is "BACNET_APPLICATION_TAG_xx" from https://github.com/stargieg/bacnet-stack/blob/master/include/bacenum.h
I suggest to use YABE (Yet Another Bacnet Explorer) for everyone, for finding right configuration values of BACnet points needed to read/write.
![image](https://user-images.githubusercontent.com/1118900/36346281-63e1a74e-1444-11e8-8e84-e2786cd70b82.png)

![image](https://user-images.githubusercontent.com/1118900/36346315-1527b78c-1445-11e8-8c06-8ce97dd0c2c5.png)
So bacnetValueType=4 in my function block.

There is my flow:
[{"id":"3d1f1a2b.ea484e","type":"tab","label":"Temperatūros","disabled":false,"info":""},{"id":"f076b690.28a4e","type":"xiaomi-home","z":"3d1f1a2b.ea484e","name":"","x":230,"y":380,"wires":[["5e33fba1.d026bc","b5109086.b0a06"]]},{"id":"f84edd62.9cd608","type":"BACnet-Write","z":"3d1f1a2b.ea484e","name":"Holo temp.","deviceIPAddress":"192.168.0.40","objectType":"2","objectInstance":"353","propertyId":"85","priority":"15","server":"2108d4fe.dbbd1c","multipleWrite":false,"x":1130,"y":380,"wires":[[]]},{"id":"5e33fba1.d026bc","type":"switch","z":"3d1f1a2b.ea484e","name":"","property":"payload.sid","propertyType":"msg","rules":[{"t":"eq","v":"158d0001fd5b5a","vt":"str"},{"t":"eq","v":"158d0001f54bab","vt":"str"},{"t":"eq","v":"158d0001f544e8","vt":"str"},{"t":"eq","v":"158d0001c2ba6c","vt":"str"},{"t":"eq","v":"158d0001f54b6b","vt":"str"},{"t":"eq","v":"158d0001f54bc6","vt":"str"}],"checkall":"true","repair":false,"outputs":6,"x":410,"y":380,"wires":[["788e4c7c.a5b484","dc3411a3.d9aff8"],["746e78ea.2b6288"],["d6d21645.15415","6ab87523.c3f50c"],["50b021b3.f3542","6c9ff0a9.6253d"],["f029bbdd.19fdf8","ad81971c.db0dd8"],["85c143e5.2901b8","1ae2ad8.84695d3"]]},{"id":"788e4c7c.a5b484","type":"debug","z":"3d1f1a2b.ea484e","name":"sveciu k.","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1220,"y":60,"wires":[]},{"id":"746e78ea.2b6288","type":"debug","z":"3d1f1a2b.ea484e","name":"laiptines t.","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":530,"y":240,"wires":[]},{"id":"d6d21645.15415","type":"debug","z":"3d1f1a2b.ea484e","name":"holo t.","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1210,"y":100,"wires":[]},{"id":"8fb97380.92c9d8","type":"debug","z":"3d1f1a2b.ea484e","name":"msg4","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":510,"y":160,"wires":[]},{"id":"b5109086.b0a06","type":"function","z":"3d1f1a2b.ea484e","name":"","func":"return {value: msg.payload.temperature};","outputs":1,"noerr":0,"x":390,"y":160,"wires":[["8fb97380.92c9d8"]]},{"id":"1fbf6886.9fdff7","type":"BACnet-Write","z":"3d1f1a2b.ea484e","name":"Saliono temp.","deviceIPAddress":"192.168.0.40","objectType":"2","objectInstance":"328","propertyId":"85","priority":"15","server":"2108d4fe.dbbd1c","multipleWrite":false,"x":1140,"y":500,"wires":[[]]},{"id":"9835d991.f21788","type":"BACnet-Write","z":"3d1f1a2b.ea484e","name":"Svečių temp.","deviceIPAddress":"192.168.0.40","objectType":"2","objectInstance":"303","propertyId":"85","priority":"15","server":"2108d4fe.dbbd1c","multipleWrite":false,"x":1130,"y":320,"wires":[[]]},{"id":"456b8ef8.17c04","type":"BACnet-Write","z":"3d1f1a2b.ea484e","name":"Miegamojo temp.","deviceIPAddress":"192.168.0.40","objectType":"2","objectInstance":"278","propertyId":"85","priority":"15","server":"2108d4fe.dbbd1c","multipleWrite":false,"x":1150,"y":440,"wires":[[]]},{"id":"63b1496b.85b96","type":"BACnet-Write","z":"3d1f1a2b.ea484e","name":"Virtuvės temp.","deviceIPAddress":"192.168.0.40","objectType":"2","objectInstance":"253","propertyId":"85","priority":"15","server":"2108d4fe.dbbd1c","multipleWrite":false,"x":1140,"y":560,"wires":[[]]},{"id":"50b021b3.f3542","type":"debug","z":"3d1f1a2b.ea484e","name":"miegamo t.","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1230,"y":140,"wires":[]},{"id":"f029bbdd.19fdf8","type":"debug","z":"3d1f1a2b.ea484e","name":"svetainės t.","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1230,"y":180,"wires":[]},{"id":"85c143e5.2901b8","type":"debug","z":"3d1f1a2b.ea484e","name":"virtuvės t.","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1220,"y":220,"wires":[]},{"id":"c239c65c.b41608","type":"function","z":"3d1f1a2b.ea484e","name":"","func":"msg.payload = {\n  bacnetValue: msg.payload.temperature,\n  bacnetValueType: 4\n\n}\n\n\n\nreturn msg;","outputs":1,"noerr":0,"x":990,"y":440,"wires":[["456b8ef8.17c04","50b021b3.f3542"]]},{"id":"2e26f3d6.206db4","type":"function","z":"3d1f1a2b.ea484e","name":"","func":"msg.payload = {\n  bacnetValue: msg.payload.temperature,\n  bacnetValueType: 4\n\n}\n\n\n\nreturn msg;","outputs":1,"noerr":0,"x":990,"y":380,"wires":[["f84edd62.9cd608","d6d21645.15415"]]},{"id":"6015b073.4c417","type":"function","z":"3d1f1a2b.ea484e","name":"","func":"msg.payload = {\n  bacnetValue: msg.payload.temperature,\n  bacnetValueType: 4\n\n}\n\n\n\nreturn msg;","outputs":1,"noerr":0,"x":990,"y":320,"wires":[["9835d991.f21788","788e4c7c.a5b484"]]},{"id":"77114731.ee476","type":"function","z":"3d1f1a2b.ea484e","name":"","func":"msg.payload = {\n  bacnetValue: msg.payload.temperature,\n  bacnetValueType: 4\n\n}\n\n\n\nreturn msg;","outputs":1,"noerr":0,"x":990,"y":500,"wires":[["1fbf6886.9fdff7","f029bbdd.19fdf8"]]},{"id":"c6292d90.80488","type":"function","z":"3d1f1a2b.ea484e","name":"","func":"msg.payload = {\n  bacnetValue: msg.payload.temperature,\n  bacnetValueType: 4\n\n}\n\n\n\nreturn msg;","outputs":1,"noerr":0,"x":990,"y":560,"wires":[["63b1496b.85b96","85c143e5.2901b8"]]},{"id":"dc3411a3.d9aff8","type":"msg-resend","z":"3d1f1a2b.ea484e","interval":"60","intervalUnit":"secs","maximum":"0","bytopic":false,"clone":true,"firstDelayed":false,"addCounters":false,"highRate":true,"outputCountField":"","outputMaxField":"","name":"","x":850,"y":320,"wires":[["6015b073.4c417"]]},{"id":"6ab87523.c3f50c","type":"msg-resend","z":"3d1f1a2b.ea484e","interval":"60","intervalUnit":"secs","maximum":"0","bytopic":false,"clone":true,"firstDelayed":false,"addCounters":false,"highRate":true,"outputCountField":"","outputMaxField":"","name":"","x":850,"y":380,"wires":[["2e26f3d6.206db4"]]},{"id":"6c9ff0a9.6253d","type":"msg-resend","z":"3d1f1a2b.ea484e","interval":"60","intervalUnit":"secs","maximum":"0","bytopic":false,"clone":true,"firstDelayed":false,"addCounters":false,"highRate":true,"outputCountField":"","outputMaxField":"","name":"","x":850,"y":440,"wires":[["c239c65c.b41608"]]},{"id":"ad81971c.db0dd8","type":"msg-resend","z":"3d1f1a2b.ea484e","interval":"60","intervalUnit":"secs","maximum":"0","bytopic":false,"clone":true,"firstDelayed":false,"addCounters":false,"highRate":true,"outputCountField":"","outputMaxField":"","name":"","x":850,"y":500,"wires":[["77114731.ee476"]]},{"id":"1ae2ad8.84695d3","type":"msg-resend","z":"3d1f1a2b.ea484e","interval":"60","intervalUnit":"secs","maximum":"0","bytopic":false,"clone":true,"firstDelayed":false,"addCounters":false,"highRate":true,"outputCountField":"","outputMaxField":"","name":"","x":850,"y":560,"wires":[["c6292d90.80488"]]},{"id":"2108d4fe.dbbd1c","type":"BACnet-Client","z":"","name":"Bacnet0","port":"","adpuTimeout":""}]

**Comment by biancode** [comment]
<img width="524" alt="grafik" src="https://user-images.githubusercontent.com/4369867/36352342-d3f4afa4-14b7-11e8-92d5-88327a598dff.png">

the release will come with the next version ...

**Comment by tadzil** [comment]
👍super

**Comment by triDcontrols** [comment]
Yes.. Can't wait. :)

**Comment by biancode** [comment]
You could test v0.0.13 but maybe it does not work, then we have to wait for the next update of [bacstack](https://github.com/fh1ch/node-bacstack/issues).

**Comment by biancode** [comment]
please test v0.1.0
