### ISSUE TITLE
Bacnet Write

### ISSUE THREAD

**Issue by mtoko** [biancode/node-red-contrib-bacnet#8]
Hi
Thanks for the great work. The read is working fine but cannot get write to work correctly. Please see screenshots and error. Any advice is appreciated
![noderedbacnet](https://user-images.githubusercontent.com/4711179/36383836-5073bd68-1585-11e8-8c14-10f82d9c0368.jpg)
![yabe](https://user-images.githubusercontent.com/4711179/36383837-5085d552-1585-11e8-970e-0b75ba981c6b.jpg)

**Comment by tadzil** [comment]
I didn't try this version yet, but there are my suggestions:
![image](https://user-images.githubusercontent.com/1118900/36389384-8f95c5a0-15a7-11e8-9b20-3b65563f7775.png)

**Comment by biancode** [comment]
please test v0.0.14

**Comment by mtoko** [comment]
Thank you for the response. I have updated to v0.0.14 restarted Node Red and re tested, there is now an error "unknown type". I have also tested with other software to ensure that the fault is not with the SB2WEB24 bacnet device and this software can operate this point. I have tried msg.payload in value and also 0/1 and true/false directly in config,also 8 and 15 in priority. Any advice is appreciated
![noderedbacnetupdate](https://user-images.githubusercontent.com/4711179/36415036-5ae0f36e-161c-11e8-89dd-c532a4cd71ef.jpg)
![noderedbacnet1](https://user-images.githubusercontent.com/4711179/36415037-5af460de-161c-11e8-8d5b-ae8cede1bacd.jpg)

**Comment by triDcontrols** [comment]
Tried 0.0.14 yesterday my self and getting same error. Tried for all 6 types. 

ANALOG OUTPUT, ANALOG INPUT, ANALOG VALUE. 

BINARY OUTPUT, BINARY INPUT, BINARY VALUE 

Same error "unknown type"

**Comment by mtoko** [comment]
I have raised the issue on Github bacstack and it appears this issue is fixed in the latest release. I have tested basic examples from Node Bacstack and writemultiple works. Could you update the node red modules and retest.
https://github.com/fh1ch/node-bacstack/issues/99

**Comment by triDcontrols** [comment]
Hi, any update to this?

**Comment by triDcontrols** [comment]
Thanks, sure does work. Instead of using the bacnet node, you are using the function requesting the bacstack and doing what the bacnet node would be doing except bacnet node isn't working. Function node works fine. I will do additional testing, but looks good. 

Sounds like all that needs to happen is @biancode would need to update the bacstack library and all would work.

**Comment by biancode** [comment]
@triDcontrols 0.0.1-beta.13 is the lastest - did I miss some? @mtoko  what about contributing to the package with your experinces from your functions source code?

**Comment by mtoko** [comment]
@biancode 
Apologies, I don't think I have the skills or experience yet to make a contribution, I still have much to learn but this has been good experience. Thank you for all your work, I have used your modbus node on many occasions and the bacnet node would be very useful. I am also monitoring the development of OPC UA

**Comment by biancode** [comment]
@mtoko I could help you to get more skills to help in development of that package if you want ;)

**Comment by biancode** [comment]
please test it with v0.0.17

**Comment by biancode** [comment]
functions like these get also TIMEOUT ERROR - just send the msg from the response and do not return msg at the end of function

`//var msg = {};
const bacnet1 = global.get('bacnet');
// Initialize BACStack
var client = bacnet1({adpuTimeout: 6000});
var state = msg.payload;

client.readProperty('192.168.1.22', {type: 4, instance: 3342490}, 85, {}, (err, value) => {
    if(err) {
        node.error(err, msg)
    }
     
    msg.payload = {value: value} ;
    node.send(msg);
})
`

**Comment by mtoko** [comment]
Thank you for all the assistance
I have tested with v0.0.17 on two different Node Red hardware but error is "unknown type" (see screenshot). I am working to understand where the problem is.
The read node still works and the "hard coded" function node to write also works
![bacwrite1](https://user-images.githubusercontent.com/4711179/39193002-75869f24-47d2-11e8-8ace-2bc15f2b844d.jpg)

**Comment by biancode** [comment]
remove msg.payload from Value and set it to 1 or 0 msg.payload is wrong here and next try to set msg.payload.values with a function node before and remove all from Value in node

**Comment by biancode** [comment]
if you set Value and App-Tag it is set to this:

```
        let defaultValues = [{
          tag: node.valueTag,
          value: node.valueValue
        }]
```

**Comment by biancode** [comment]
please read [API Docs ](https://fh1ch.github.io/node-bacstack/bacstack.html#.writeProperty)- maybe you use a old version of bacstack from npm global

**Comment by mtoko** [comment]
I did see that tag/type on line 93 of write.js. I changed this on my local write.js to type but it did not fix the problem

**Comment by biancode** [comment]
`[{"id":"d60cced6.cc4198","type":"function","z":"3345fb9d.6eee74","name":"Yabe Room Simulator and Weather2","func":"const BACnet = global.get('bacnet');\nconst client = new BACnet();\n\n// discover devices\nclient.on('iAm', function(device) {\n  const msg = { payload: {\n      \"address\": device.address,\n      \"deviceId\": device.deviceId,\n      \"maxAdpu\": device.maxAdpu,\n      \"segmentation\": device.segmentation,\n      \"vendorId\": device.vendorId\n    }\n  }\n  node.send(msg);\n});\n\nclient.whoIs();\n \n// Read Device Object\nvar requestArray = [{\n  objectId: {type: 8, instance: 12345},\n  properties: [{id: 8}]\n}];\nclient.readPropertyMultiple('192.168.1.22', requestArray, function(err, value) {\n    if(err) {\n        node.error(err, msg)\n    }\n     \n    msg.payload = {value: value, error: err} ;\n    node.send(msg);\n});\n\nclient.readProperty('192.168.1.22', {type: 8, instance: 12345}, 77, (err, value) => {\n    if(err) {\n        node.error(err, msg)\n    }\n     \n    msg.payload = {value: value, error: err} ;\n    node.send(msg);\n})\n\n\nrequestArray = [\n  {objectId: {type: 8, instance: 12345}, properties: [{id: 8}, {id: 77}]},\n  {objectId: {type: 8, instance: 3342490}, properties: [{id: 85}, {id: 8}]}\n];\nclient.readPropertyMultiple('192.168.1.22', requestArray, (err, value) => {\n    if(err) {\n        node.error(err, msg)\n    }\n    \n    msg.payload = {value: value, error: err} ;\n    node.send(msg);\n});","outputs":1,"noerr":0,"x":470,"y":60,"wires":[["a398b63a.9ebde"]]},{"id":"b29fecfb.5934a","type":"inject","z":"3345fb9d.6eee74","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":60,"wires":[["d60cced6.cc4198"]]},{"id":"a398b63a.9ebde","type":"debug","z":"3345fb9d.6eee74","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":730,"y":60,"wires":[]}]`

**Comment by biancode** [comment]
[bacstack issues](https://github.com/fh1ch/node-bacstack/issues)

**Comment by mtoko** [comment]
The flow above with the function node works, but it should do because it is a read and there are no problems with read. The Yabe flow has problems in the function node, I think the problem is BOOLEAN and value of 100? I have only got ENUMERATED to work. See this working write flow


[{"id":"23988557.fae66a","type":"inject","z":"143b8cb5.c27573","name":"","topic":"","payload":"1","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":270,"y":100,"wires":[["58d0ace5.2d73f4"]]},{"id":"ed31364a.5ad958","type":"inject","z":"143b8cb5.c27573","name":"","topic":"","payload":"0","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":270,"y":160,"wires":[["58d0ace5.2d73f4"]]},{"id":"58d0ace5.2d73f4","type":"function","z":"143b8cb5.c27573","name":"Boiler 1","func":"//var msg = {};\nconst bacnet1 = global.get('bacnet');\n// Initialize BACStack\nvar client = bacnet1({adpuTimeout: 6000});\nvar state = msg.payload;\n\nconst values = [\n  {objectId: {type: 4, instance: 0}, values: [\n    {property: {id: 85, index: 4294967295}, value: [{type: bacnet1.enum.ApplicationTags.BACNET_APPLICATION_TAG_ENUMERATED, value: state}], priority: 15}\n  ]}\n];\nclient.writePropertyMultiple('192.168.1.135', values, (err, value) => {\n  msg.payload = {value: value} ;\n  \n  if(err) { msg.payload = {error: err} ; }\n  node.send(msg);\n});\n\nclient.readProperty('192.168.1.135', {type: 4, instance: 0}, 85, (err, value) => {\n  msg.payload = {value: value} ;\n  node.send(msg);\n})\n\n","outputs":1,"noerr":0,"x":440,"y":120,"wires":[[]]}]

**Comment by biancode** [comment]
v0.0.18 is now type and not tag for write

**Comment by mtoko** [comment]
Upgrade to v0.0.18 error is still unknown type

Sorry
Could you share an example of function node in earlier mesage
set msg.payload.values with a function node

**Comment by biancode** [comment]
![grafik](https://user-images.githubusercontent.com/4369867/39205843-29c99cc4-47fc-11e8-9fc7-79aa4f86365b.png)

**Comment by mtoko** [comment]
I have tried the flow below and get this bacnet error. I have used values from previous working function node. The client is correct because the reads are still working
![bacwrite2](https://user-images.githubusercontent.com/4711179/39207501-073895ec-47f8-11e8-817a-d4b0c787086a.jpg)

Flow

[{"id":"e74b4da5.ee62f","type":"inject","z":"70e6f53f.47c17c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":100,"wires":[["a94a766d.a10d18"]]},{"id":"ee1854cb.e0b6e8","type":"inject","z":"70e6f53f.47c17c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":160,"wires":[["7d33a68e.a4bc58"]]},{"id":"8d99ef57.02049","type":"BACnet-Write","z":"70e6f53f.47c17c","name":"","deviceIPAddress":"192.168.1.135","objectType":"","objectInstance":"","valueTag":"","valueValue":"","propertyId":"85","arrayIndex":"4294967295","server":"28e8a4b2.188ccc","multipleWrite":false,"x":680,"y":140,"wires":[[]]},{"id":"a94a766d.a10d18","type":"function","z":"70e6f53f.47c17c","name":"","func":"msg.payload.values = [\n    {\n        \"objectId\": { type: 4, instance:0 },\n        \"values\": [\n            {\n                \"property\": {id: 85, index: 4294967295},\n                \"value\": [{type: 9, value: 0}],\n                \"priority\": 15\n    \n            }\n            ]\n        \n    }\n\n    ];\nreturn msg;","outputs":1,"noerr":0,"x":410,"y":100,"wires":[["8d99ef57.02049"]]},{"id":"7d33a68e.a4bc58","type":"function","z":"70e6f53f.47c17c","name":"","func":"msg.payload.values = [\n    {\n        \"objectId\": { type: 4, instance:0 },\n        \"values\": [\n            {\n                \"property\": {id: 85, index: 4294967295},\n                \"value\": [{type: 9, value: 1}],\n                \"priority\": 15\n    \n            }\n            ]\n        \n    }\n\n    ];\nreturn msg;","outputs":1,"noerr":0,"x":410,"y":160,"wires":[["8d99ef57.02049"]]},{"id":"28e8a4b2.188ccc","type":"BACnet-Client","z":"","name":"","adpuTimeout":"3000","port":"47808","interface":"192.168.1.132","broadcastAddress":"192.168.1.255"}]

**Comment by biancode** [comment]
@fh1ch could you tell us more, please?
