### ISSUE TITLE
ERR_TIMEOUT

### ISSUE THREAD

**Issue by nomadbeni** [biancode/node-red-contrib-bacnet#9]
Hello,
I am trying to use thid node and have a problem and a question.
Problem: 
I can set up the bacnet read node, and it works well. 
But when I try to use bacnet write, and I probably use it the wrong way, bacnet read gives this error: ERR_TIMEOUT.
Question: Can you upload some howto about the bacnet write? Maybe a sample code.

**Comment by biancode** [comment]
I am sorry, not for now ...
